export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const CHECK_USER_IN_SYSTEM_SUCCESS = "CHECK_USER_IN_SYSTEM_SUCCESS";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const USER_UPDATE_SETTINGS_SUCCESS = "USER_UPDATE_SETTINGS_SUCCESS";
export const REQUEST_ERROR = "REQUEST_ERROR";
